Improved GDScript.tmLanguage.json
godotengine/godot-vscode-plugin pull request #740
Opened 2024-10-20 19:57 UTC by nodlag

Added:
as
@export_category
#region
#endregion

Improved to better colors themes:
int|float|bool

Improved nodepath vars like this example:
@onready var grid_ui: CanvasLayer = $GridUI
@onready var grid_container: GridContainer = $GridUI/MarginContainer/GridContainer

Improved const color

2024-10-24 00:02 UTC, Calinou approved these changes
Makes sense to me.

Please rebase to fix merge conflicts :slightly_smiling_face: See [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

2024-10-24 12:59 UTC, DaelonSuzuka requested changes

2024-10-24 12:59 UTC, DaelonSuzuka commented on syntaxes/GDScript.tmLanguage.json
> +				"2": { "name": "constant.language.gdscript" }
This is overwriting a change that was just merged in #737, please revert this.

2024-10-24 13:05 UTC, nodlag commented on syntaxes/GDScript.tmLanguage.json
> +					"match": "(:)\\s*\\b(int|float|bool)\\b",
Because in Godot the 3 vars are highlighted separated than others. I not sure if more vars types are like this 3.

2024-10-24 13:06 UTC, nodlag commented on syntaxes/GDScript.tmLanguage.json
> +			"match": "(@)(export|export_color_no_alpha|export_custom|export_category|export_dir|export_enum|export_exp_easing|export_file|export_flags|export_flags_2d_navigation|export_flags_2d_physics|export
Yes I didn't see static_unload because when i push the first changes it wasn't. You are right.

2024-10-24 13:07 UTC, nodlag commented on syntaxes/GDScript.tmLanguage.json
> +			"match": "(?<![^.]\\.|:)\\b(Vector2|Vector2i|Vector3|Vector3i|Color|Rect2|Rect2i|Array|Basis|Dictionary|Plane|Quat|RID|Rect3|Transform|Transform2D|Transform3D|AABB|String|Color|NodePath|PoolByteAr
The same of the previous comment.

2024-10-24 13:08 UTC, nodlag commented on syntaxes/GDScript.tmLanguage.json
> +			"name": "constant.language.boolean.gdscript"
Right it was for the highlighting. This should be separated.

2024-10-24 13:13 UTC, nodlag commented
I have reverted, I will fix properly.

2024-10-24 16:42 UTC, DaelonSuzuka commented on syntaxes/GDScript.tmLanguage.json
> +			"name": "constant.language.boolean.gdscript"
`constant.language` and `constant.language.boolean` appear to be highlighted the same, so I don't know what you mean here.

2024-10-24 16:51 UTC, DaelonSuzuka commented on syntaxes/GDScript.tmLanguage.json
> +					"match": "(:)\\s*\\b(int|float|bool)\\b",
Sounds like Godot is wrong, then.

2024-11-22 21:35 UTC, Robert-K commented
`export_group` should also be added to the annotations, it's not matched atm

2024-11-30 18:53 UTC, closed without merging